### ISSUE TITLE
生命周期图示翻译有误

### ISSUE THREAD

**Issue by YuyanCloud** [vuejs/cn.vuejs.org#1047]
图示中  "将el外部的HTML作为template编译*"  中的  "外部的HTML"  应直译为  "outerHTML"
因为"outerHTML"与"innerHTML"同样为html元素属性,不应被翻译为中文

**Comment by Sefank** [comment]
Sorry for the mistake. However, since"outerHTML" has its own actual meaning, it would be better if "outerHTML" remains in the main body and the translation can be left aside in small-font note (as other similar cases in the image).
If you would like to help, you can find the translated .psd file at #967 , edit it and push your PR. Your effort would be appreciated. (Note that the font used in the image should be installed first if you would like to edit.)

**Comment by Jinjiang** [comment]
Anyone could help us to modify the .psd file and export a new image? Or I will revert this image back to the original one. Thanks.

**Comment by YuyanCloud** [comment]
> Anyone could help us to modify the .psd file and export a new image? Or I will revert this image back to the original one. Thanks.

I'll try it, I'm worried about messing it up

**Comment by Jinjiang** [comment]
No worry, could feel free to try :-)
